# This is a basic workflow to help you get started with Actions

name: CI-dev

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: ' Env to run test against'
        type: string
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: print a secret
        env: 
          LWDC_SECRET: ${{ secrets.LWDC_SECRET_1 }}
        run: echo Secret LWDC_SECRET_1 is $LWDC_SECRET
        
      - name: print a environment secret
        env: 
          DEV_LWDC_SECRET: ${{ secrets.LWDC_DEV_SECRET_1 }}
        run: echo Secret LWDC_SECRET_1 is $DEV_LWDC_SECRET

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script 
        run: |
          echo Printing input parameters passed
          echo The value of environemnet is ${{ inputs.environment }}
